// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdoqdznlozfecfapogwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtkb3Fkem5sb3pmZWNmYXBvZ3dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MTA0MTIsImV4cCI6MjA2MDI4NjQxMn0.8IyTqBV7ZEG_fmBxWwgq9TIPd5opLL2UD3LtT8Du_CE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);